title: Hey! It's ADITYA here
description: This page is a professional introduction about me
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
social-network-links:
  rss: true
  email: "someone@example.com"
  facebook: deanattali
  github: daattali
  twitter: daattali
